# Generated by Django 2.0.9 on 2018-11-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Aula', models.CharField(max_length=130)),
                ('Numero_Alumnos', models.IntegerField()),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
