# Generated by Django 2.0.9 on 2018-11-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aulas',
            new_name='Aula',
        ),
    ]
