# Generated by Django 2.0.9 on 2018-11-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20181103_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Grado', models.CharField(max_length=130)),
                ('Nivel', models.CharField(choices=[('Pre-Primaria', 'Primaria'), ('Basico', 'Diversificado')], default='Pre-Primaria', max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='grado',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Aula'),
        ),
    ]
