# Generated by Django 2.0.9 on 2018-11-04 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0005_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=200)),
                ('SegundoNombre', models.CharField(max_length=200)),
                ('TercerNombre', models.CharField(blank=True, max_length=200, null=True)),
                ('PrimerApellido', models.CharField(max_length=200)),
                ('SegundoApellido', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=7)),
                ('nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('PendienteExamen', 'Pendiente Examen'), ('PendienteInscripcion', 'PendienteInscripcion')], default='Inactivo', max_length=20)),
                ('fechaingreso', models.DateTimeField(blank=True, null=True)),
                ('Creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Grado')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='Creado',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
