# Generated by Django 2.0.9 on 2018-11-04 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20181103_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecargados_alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('telefono_celular', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=200)),
                ('Trabajo', models.CharField(max_length=200)),
                ('telefono_trabajo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('PendienteExamen', 'Pendiente Examen'), ('PendienteInscripcion', 'PendienteInscripcion')], default='Inactivo', max_length=20)),
                ('fechaingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ecargados_alumnos',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno'),
        ),
        migrations.AddField(
            model_name='ecargados_alumnos',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Encargado'),
        ),
    ]
