# Generated by Django 2.0.9 on 2018-11-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20181103_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Boleta', models.CharField(max_length=200)),
                ('Comentario', models.CharField(max_length=200)),
                ('Estado_Examen', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendiente', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='genero',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='grado',
            new_name='Grado',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='PrimerApellido',
            new_name='Primer_Apellido',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='PrimerNombre',
            new_name='Primer_Nombre',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='SegundoApellido',
            new_name='Segundo_Apellido',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='SegundoNombre',
            new_name='Segundo_Nombre',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='TercerNombre',
            new_name='Tercer_Nombre',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='aula',
            new_name='Aula',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno'),
        ),
    ]
