# Generated by Django 2.0.9 on 2018-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20181104_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examene',
            name='Comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
