# Generated by Django 2.0.9 on 2018-11-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='Tipo_Pago',
            field=models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Inscripcion', max_length=20),
        ),
    ]
