# Generated by Django 2.0.9 on 2018-11-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_auto_20181104_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='Cantidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
