# Generated by Django 2.0.9 on 2018-11-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_pago_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papeleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alergias', models.CharField(blank=True, max_length=200, null=True)),
                ('Enfermedades', models.CharField(blank=True, max_length=200, null=True)),
                ('Nombre_Doctor', models.CharField(blank=True, max_length=200, null=True)),
                ('Telefono_Doctor', models.CharField(blank=True, max_length=200, null=True)),
                ('Certificado_Pre_Primaria', models.CharField(choices=[('Recibido', 'Recibido'), ('No_Entregado', 'No Entregado'), ('No_Cuenta_Con', 'No Cuenta Con')], default='No_Entregado', max_length=30)),
                ('Certificado_Primaria', models.CharField(choices=[('Recibido', 'Recibido'), ('No_Entregado', 'No Entregado'), ('No_Cuenta_Con', 'No Cuenta Con')], default='No_Entregado', max_length=30)),
                ('Certificado_Basico', models.CharField(choices=[('Recibido', 'Recibido'), ('No_Entregado', 'No Entregado'), ('No_Cuenta_Con', 'No Cuenta Con')], default='No_Entregado', max_length=30)),
                ('Certificado_Bachillerato', models.CharField(choices=[('Recibido', 'Recibido'), ('No_Entregado', 'No Entregado'), ('No_Cuenta_Con', 'No Cuenta Con')], default='No_Entregado', max_length=30)),
                ('Tipo_Sangre', models.CharField(blank=True, choices=[('Desconocido', 'Desconocido'), ('O_negativo', 'O negativo'), ('O_positivo', 'O positivoo'), ('A_negativo', 'A negativo'), ('A_positivo', 'A positivo'), ('B_negativo', 'B negativo'), ('B_positivo', 'B positivo'), ('AB_negativo', 'AB negativo'), ('AB_positivo', 'AB positivo')], default='Desconocido', max_length=30, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=200, null=True)),
                ('Alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='encargado',
            name='Dpi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='papeleria',
            name='Madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Madre', to='administracion.Encargado'),
        ),
        migrations.AddField(
            model_name='papeleria',
            name='Padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Padre', to='administracion.Encargado'),
        ),
    ]
