# Generated by Django 2.0.9 on 2018-11-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_auto_20181104_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grados_Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Materia', models.CharField(max_length=130)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='papeleria',
            name='Partida_Nacimiento',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('No_Entregado', 'No Entregado'), ('No_Cuenta_Con', 'No Cuenta Con')], default='No_Entregado', max_length=30),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='Trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='telefono_casa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grados_materias',
            name='Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Materia'),
        ),
    ]
