# Generated by Django 2.0.9 on 2018-11-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_auto_20181104_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres_Personal', models.CharField(max_length=200)),
                ('Apellidos_Personal', models.CharField(max_length=200)),
                ('Telefono_Casa', models.CharField(blank=True, max_length=200, null=True)),
                ('Telefono_Celular', models.CharField(blank=True, max_length=200, null=True)),
                ('Direccion', models.CharField(max_length=128, verbose_name='address')),
                ('Dpi', models.CharField(max_length=20)),
                ('Estado_Civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorsiado', 'Divorsiado')], default='Soltero', max_length=20)),
                ('Fecha_Nacimiento', models.DateTimeField(blank=True, null=True)),
                ('Lugar_Nacimiento', models.CharField(max_length=128, verbose_name='address')),
                ('No_Hijos', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorsiado', 'Divorsiado')], default='hijos', max_length=20)),
                ('Nit', models.CharField(max_length=20)),
                ('Igss', models.CharField(max_length=30)),
                ('Fecha_Inicio_Labores', models.DateTimeField(blank=True, null=True)),
                ('Nivel_Academico', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=50)),
                ('Cedula_Docente', models.CharField(max_length=50)),
                ('Registro_Escalafonario', models.CharField(max_length=50)),
                ('Salario', models.CharField(max_length=50)),
                ('fechaingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
