# Generated by Django 2.0.9 on 2018-11-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_auto_20181104_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignacion_Materias',
            new_name='Asignacion_Materia',
        ),
    ]
