# Generated by Django 2.0.9 on 2018-11-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_auto_20181104_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Fecha_Inicio_Labores',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Fecha_Nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
