# Generated by Django 2.0.9 on 2018-11-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_auto_20181104_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='Apellidos_Personal',
            new_name='Primer_Apellido',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Nombres_Personal',
            new_name='Primer_Nombre',
        ),
        migrations.AddField(
            model_name='personal',
            name='Segundo_Apellido',
            field=models.CharField(default='Sin', max_length=200),
        ),
        migrations.AddField(
            model_name='personal',
            name='Segundo_Nombre',
            field=models.CharField(default='Sin', max_length=200),
        ),
    ]
