# Generated by Django 2.0.9 on 2018-11-05 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_auto_20181104_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Acividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Actividad', models.CharField(choices=[('Act1', 'Actividad 1'), ('Act2', 'Actividad 2'), ('Act3', 'Actividad 3'), ('Act4', 'Actividad 4'), ('Act5', 'Actividad 5'), ('Act6', 'Actividad 6'), ('Act7', 'Actividad 7'), ('Act8', 'Actividad 8'), ('Act9', 'Actividad 9'), ('Act10', 'Actividad 10'), ('Exa', 'Examen Final')], default='Actividad 1', max_length=20)),
                ('Descripcion_Actividad', models.CharField(max_length=200)),
                ('Ponderacion', models.IntegerField()),
                ('Asignacion_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Asignacion_Materia')),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='Segundo_Apellido',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Segundo_Nombre',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
