# Generated by Django 2.0.9 on 2018-11-05 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_auto_20181104_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_acividades',
            name='Ponderacion',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)]),
        ),
    ]
