# Generated by Django 2.0.9 on 2018-11-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_auto_20181104_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignacion_Acividades',
            new_name='Asignacion_Acividade',
        ),
    ]
