# Generated by Django 2.0.9 on 2018-11-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_auto_20181104_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Hora_Entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='Hora_Salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
