# Generated by Django 2.0.9 on 2018-11-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_auto_20181104_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_acividade',
            name='Unidad',
            field=models.CharField(choices=[('uni1', 'Primera Unidad'), ('uni2', 'Segunda Unidad'), ('uni3', 'Tercera Unidad'), ('uni4', 'Cuarta Unidad')], default='Primera Unidad', max_length=20),
        ),
    ]
