# Generated by Django 2.0.9 on 2018-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_asignacion_acividade_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('PendienteExamen', 'Pendiente De Examen'), ('PendienteInscripcion', 'Pendiente De Inscripcion')], default='Inactivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='examene',
            name='Estado_Examen',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Tipo_Pago',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Seguro', 'Seguro'), ('Inscripcion', 'Inscripcion'), ('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre'), ('Otro', 'Otro')], default='Inscripcion', max_length=20),
        ),
    ]
