# Generated by Django 2.0.9 on 2018-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_auto_20181109_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=7),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Segundo_Nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Tipo_Pago',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Seguro', 'Seguro'), ('Inscripcion', 'Inscripcion'), ('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Otro', 'Otro')], default='Inscripcion', max_length=20),
        ),
    ]
