# Generated by Django 2.0.9 on 2018-11-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_auto_20181110_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Primer_Apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Segundo_Apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
