# Generated by Django 2.0.9 on 2018-11-12 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0031_auto_20181111_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Creado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
