# Generated by Django 2.0.9 on 2018-11-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0032_auto_20181111_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ecargados_alumnos',
            new_name='Encargados_alumnos',
        ),
    ]
