# Generated by Django 2.0.9 on 2018-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_auto_20181112_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargados_alumnos',
            name='parentesco',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
