# Generated by Django 2.0.9 on 2018-11-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0034_encargados_alumnos_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='examene',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
