# Generated by Django 2.0.9 on 2018-11-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0036_papeleria_cui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Codigo',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='examene',
            name='Alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno', unique=True),
        ),
    ]
