# Generated by Django 2.0.9 on 2018-11-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0037_auto_20181115_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examene',
            name='Alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno'),
        ),
    ]
