# Generated by Django 2.0.9 on 2018-11-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0038_auto_20181115_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='telefono2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
