# Generated by Django 2.0.9 on 2018-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0039_alumno_telefono2'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=120)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Fecha_Inicio', models.DateTimeField(blank=True, null=True)),
                ('Fecha_Fin', models.DateTimeField(blank=True, null=True)),
                ('Grupo', models.CharField(choices=[('estu-preprimaria', 'Estudiantes Pre-Primaria'), ('estu-primaria', 'Estudiantes Primaria'), ('estu-basico', 'Estudiantes Basico'), ('estu-bach', 'Estudiantes Bachillerato'), ('prof-preprimaria', 'Profesores Pre-Primaria'), ('prof-primaria', 'Profesores Primaria'), ('prof-basico', 'Profesores Basico'), ('profbach', 'Profesores Bachillerato'), ('todos', 'Todos')], default='Todos', max_length=30)),
            ],
        ),
    ]
