# Generated by Django 2.0.9 on 2018-12-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0040_actividades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='actividades',
            new_name='Actividade',
        ),
    ]
