# Generated by Django 2.0.9 on 2018-12-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0041_auto_20181211_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividade',
            name='Fecha_Fin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='actividade',
            name='Fecha_Inicio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
