# Generated by Django 2.0.9 on 2018-12-14 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0042_auto_20181211_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Creado',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
