# Generated by Django 2.0.9 on 2018-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0043_auto_20181213_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
