# Generated by Django 2.0.9 on 2018-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0044_alumno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='Lugar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('PendienteExamen', 'Pendiente De Examen'), ('PendienteInscripcion', 'Pendiente De Inscripcion'), ('PendientePago', 'Pendiente De Pago')], default='Inactivo', max_length=20),
        ),
    ]
