# Generated by Django 2.0.9 on 2018-12-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0045_auto_20181227_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividade',
            name='Especifico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
