# Generated by Django 2.0.9 on 2019-01-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0046_actividade_especifico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno')),
            ],
        ),
    ]
