# Generated by Django 2.0.9 on 2019-01-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0047_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=200)),
                ('Permiso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.Permiso')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asignacion_permiso',
            unique_together={('Permiso', 'Usuario')},
        ),
    ]
