# Generated by Django 2.0.9 on 2019-01-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0048_auto_20190109_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
