# Generated by Django 2.0.9 on 2019-01-10 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0050_auto_20190109_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_permiso',
            name='Usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
