# Generated by Django 2.0.9 on 2019-01-10 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0051_auto_20190109_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_permiso',
            name='Permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Permiso'),
        ),
        migrations.AlterField(
            model_name='asignacion_permiso',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
