# Generated by Django 2.0.9 on 2019-01-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0052_auto_20190110_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_materia',
            name='Seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion_materia',
            unique_together={('Grado', 'Materia', 'Seccion')},
        ),
    ]
