# Generated by Django 2.0.9 on 2019-01-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0053_auto_20190110_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seccion', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=7)),
                ('Grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Grado')),
                ('Personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Personal')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asignacion_grado',
            unique_together={('Grado', 'Seccion')},
        ),
    ]
