# Generated by Django 2.0.9 on 2019-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0054_auto_20190110_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Cedula_Docente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Nivel_Academico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Registro_Escalafonario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Salario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
