# Generated by Django 2.0.9 on 2019-01-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0056_personal_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Punteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.IntegerField(default=0)),
                ('Alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno')),
                ('Asignacion_Acividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Asignacion_Acividade')),
            ],
        ),
    ]
