# Generated by Django 2.0.9 on 2019-01-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0057_asignacion_punteo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacion_acividade',
            unique_together={('Asignacion_Materia', 'Unidad', 'Nombre_Actividad')},
        ),
    ]
