# Generated by Django 2.0.9 on 2019-01-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0058_auto_20190112_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_punteo',
            name='Alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion_punteo',
            unique_together={('Asignacion_Acividades', 'Alumno')},
        ),
    ]
