# Generated by Django 2.0.9 on 2019-01-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0059_auto_20190113_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_acividade',
            name='Ponderacion',
            field=models.CharField(max_length=3),
        ),
    ]
