# Generated by Django 2.0.9 on 2019-01-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0060_auto_20190113_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
