# Generated by Django 2.0.10 on 2019-02-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0061_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_permiso',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
