# Generated by Django 2.0.10 on 2019-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0062_asignacion_permiso_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion_permiso',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='asignacion_permiso',
            name='Estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
