# Generated by Django 2.0.10 on 2019-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0063_auto_20190211_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_punteo',
            name='Estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('No_Aprobado', 'No Aprobado'), ('Aprobado', 'Aprobado')], default='No_Aprobado', max_length=20),
        ),
    ]
