# Generated by Django 2.0.10 on 2019-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0064_asignacion_punteo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(choices=[('Pre-Primaria', 'Pre-Primaria'), ('Primaria', 'Primaria'), ('Basico', 'Basico'), ('Diversificado', 'Diversificado')], default='Pre-Primaria', max_length=100)),
                ('hora_inicio', models.CharField(max_length=50)),
                ('hora_fin', models.CharField(max_length=50)),
            ],
        ),
    ]
