# Generated by Django 2.0.10 on 2019-02-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0065_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Registro', 'Registro'), ('Inactivo', 'Inactivo'), ('PendienteExamen', 'Pendiente De Examen'), ('PendienteInscripcion', 'Pendiente De Inscripcion'), ('PendientePago', 'Pendiente De Pago')], default='Inactivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Direccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Dpi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Estado_Civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorsiado', 'Divorsiado')], default='Soltero', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Igss',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Lugar_Nacimiento',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Segundo_Nombre',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
