# Generated by Django 2.0.10 on 2019-03-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0066_auto_20190224_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion_materias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Asignacion_Materia')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='horas',
            unique_together={('Nivel', 'hora_inicio')},
        ),
        migrations.AddField(
            model_name='periodos',
            name='horas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.horas'),
        ),
    ]
