# Generated by Django 2.0.10 on 2019-03-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0067_auto_20190310_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periodos',
            new_name='Periodo',
        ),
    ]
