# Generated by Django 2.0.10 on 2019-03-11 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0068_auto_20190310_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='Lunes', max_length=100),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='horas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.horas'),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('dia', 'horas')},
        ),
    ]
