# Generated by Django 2.0.10 on 2019-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0069_auto_20190310_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='Seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=7),
        ),
    ]
