# Generated by Django 2.0.10 on 2019-03-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0070_periodo_seccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('asignacion_materias', 'dia', 'horas')},
        ),
    ]
