# Generated by Django 2.0.10 on 2019-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0071_auto_20190325_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividade',
            name='Grupo',
            field=models.CharField(choices=[('estudiantes', 'Todos los Estudiantes'), ('profesores', 'Todos los Profesores'), ('estu-preprimaria', 'Estudiantes Pre-Primaria'), ('estu-primaria', 'Estudiantes Primaria'), ('estu-basico', 'Estudiantes Basico'), ('estu-bach', 'Estudiantes Bachillerato'), ('prof-preprimaria', 'Profesores Pre-Primaria'), ('prof-primaria', 'Profesores Primaria'), ('prof-basico', 'Profesores Basico'), ('profbach', 'Profesores Bachillerato'), ('todos', 'Todos')], default='Todos', max_length=30),
        ),
    ]
