# Generated by Django 2.0.10 on 2019-05-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0073_auto_20190427_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_punteo',
            name='Estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('No_Aprobado', 'No Aprobado'), ('Aprobado', 'Aprobado')], default='No Aprobado', max_length=20),
        ),
    ]
