# Generated by Django 2.0.10 on 2019-07-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0074_auto_20190511_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioexamen',
            name='dia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
