# Generated by Django 2.0.10 on 2019-07-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0075_auto_20190723_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seccion', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=7)),
                ('contenido', models.CharField(max_length=100)),
                ('pagina', models.CharField(blank=True, max_length=100, null=True)),
                ('asignacion_materias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Asignacion_Materia')),
            ],
        ),
        migrations.CreateModel(
            name='notas_examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.CharField(blank=True, max_length=50, null=True)),
                ('Nivel', models.CharField(default='Todos', max_length=100)),
                ('Activo', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contenidoexamen',
            unique_together={('asignacion_materias', 'contenido')},
        ),
    ]
