# Generated by Django 2.0.10 on 2019-08-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0076_auto_20190725_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('Solucion', models.CharField(blank=True, max_length=200, null=True)),
                ('Tipo', models.CharField(choices=[('Conducta', 'Conducta'), ('Tarea', 'Tarea'), ('Otros', 'Otros')], default='Otros', max_length=20)),
                ('Fecha_Ingreso', models.DateTimeField(blank=True, null=True)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Alumno')),
                ('Personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Personal')),
            ],
        ),
        migrations.AddField(
            model_name='contenidoexamen',
            name='Unidad',
            field=models.CharField(choices=[('uni1', 'Primera Unidad'), ('uni2', 'Segunda Unidad'), ('uni3', 'Tercera Unidad'), ('uni4', 'Cuarta Unidad')], default='Primera Unidad', max_length=20),
        ),
    ]
