# Generated by Django 2.0.10 on 2019-09-06 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0077_auto_20190830_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidad', models.CharField(choices=[('uni1', 'Primera Unidad'), ('uni2', 'Segunda Unidad'), ('uni3', 'Tercera Unidad'), ('uni4', 'Cuarta Unidad')], default='Primera Unidad', max_length=20)),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No_Aprobado', 'No Aprobado'), ('Aprobado', 'Aprobado')], default='No Aprobado', max_length=20)),
                ('asignacion_materias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.Asignacion_Materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='asignacion_punteo',
            name='Estado',
        ),
        migrations.AlterField(
            model_name='reportes',
            name='Fecha_Ingreso',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='estados_materia',
            unique_together={('asignacion_materias', 'Unidad')},
        ),
    ]
