# Generated by Django 2.0.10 on 2019-11-08 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0078_auto_20190906_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='examene',
            name='Comentario_Idioma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Comentario_Ingles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Comentario_Matematicas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examene',
            name='Estado_Idioma',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Nivelacion', 'Nivelacion')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='examene',
            name='Estado_Ingles',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Nivelacion', 'Nivelacion')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='examene',
            name='Estado_Matematicas',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Nivelacion', 'Nivelacion')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='examene',
            name='Nota_Idioma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examene',
            name='Nota_Ingles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examene',
            name='Nota_Matematicas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materia',
            name='Fecha_Ingreso',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
