# Generated by Django 2.0.10 on 2020-03-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0081_auto_20200313_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='Fecha_Solucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
